export const GET_HOW_WORK_CONTENT_START = "GET_HOW_WORK_CONTENT_START";
export const GET_HOW_WORK_CONTENT_SUCCESS = "GET_HOW_WORK_CONTENT_SUCCESS";
export const GET_HOW_WORK_CONTENT_FAIL = "GET_HOW_WORK_CONTENT_FAIL";